### ISSUE TITLE
README: flights-200k.arrow example file not readable with flechette

### ISSUE THREAD

**Issue by dvdkouril** [uwdata/flechette#26]
Hi, I noticed that the minimal example from README that uses the `flights-200k.arrow` dataset:
```javascript
import { tableFromIPC } from '@uwdata/flechette';

const url = 'https://vega.github.io/vega-datasets/data/flights-200k.arrow';
const ipc = await fetch(url).then(r => r.arrayBuffer());
const table = tableFromIPC(ipc);

// print table size: (231083 x 3)
console.log(`${table.numRows} x ${table.numCols}`);
```
returns `Error: Record batch compression not implemented`. Hope that I'm not missing something, just tried it with deno and in browser.

Seems like the [flights datasets were changed recently](https://github.com/vega/vega-datasets/pull/645) in the vega-datasets repo?

**Comment by jheer** [comment]
Thanks! I raised an issue with vega-datasets: https://github.com/vega/vega-datasets/issues/655

I'll also look into updating the README with alternative example data later.

**Comment by jheer** [comment]
README.md and docs page now updated with stable, working URL.
