### ISSUE TITLE
More JSDoc annotations?

### ISSUE THREAD

**Issue by manzt** [uwdata/flechette#4]
Really cool to stumble across this. I pulled down the repo and started digging through the code base. I started adding some more type annotations to help orient myself.

Would you be open to a PR gradually typing more of the code base with JSDoc-style TypeScript?

**Comment by jheer** [comment]
Thanks, sounds good to me!

**Comment by jheer** [comment]
Hi @manzt, I'm going to close out this issue. FYI there has been a lot of recent churn on Flechette. If you are still interested in opening PRs for improved typings or documentation, please feel free!

**Comment by manzt** [comment]
Thanks! Yeah sorry this was premature... i've been a bit tied down with wrapping up my phd and got really excited with the initial release!
